# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        if: ${{ github.ref == 'ref/heads/main' }}
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rlgoDzvc -i"
            SOURCE: "./"
            REMOTE_HOST: ${{ vars.REMOTE_HOST }}
            REMOTE_USER: "root"
            TARGET: "/tmp/ogotest"
            EXCLUDE: "/dist/, /node_modules/, .git, .github, 555"


      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: touch /tmp/ggopatest 
        if: ${{ github.ref == 'ref/heads/dev' }}
